Mission 3
0dens1337/ToDo_list pull request #2
Opened 2024-06-06 14:59 UTC by 0dens1337

2024-06-06 15:23 UTC, dnlzv requested changes

2024-06-06 15:23 UTC, danilapetrukhin commented on app/Http/Controllers/Auth/ConfirmablePasswordController.php
> +            'password' => $request->password,
Вынеси в отдельный FromRequest. Да я знаю что это сделал Laravel Breeze. Лучше написать это более красиво и соблюдать принцип плоских контроллеров.

2024-06-06 15:23 UTC, danilapetrukhin commented on app/Http/Controllers/Auth/NewPasswordController.php
> +            'password' => ['required', 'confirmed', Rules\Password::defaults()],
Вынести в отдельный FormRequest

2024-06-06 15:23 UTC, danilapetrukhin commented on app/Http/Controllers/Auth/NewPasswordController.php
> +            }
Здесь поправить, когда вынесешь валидацию

2024-06-06 15:23 UTC, danilapetrukhin commented on app/Http/Controllers/Auth/RegisteredUserController.php
> +        ]);
Тоже самое

2024-06-06 15:23 UTC, danilapetrukhin commented on app/Http/Controllers/Auth/RegisteredUserController.php
> +        ]);
Поправить с изменениями

2024-06-06 15:23 UTC, danilapetrukhin commented on app/Providers/RouteServiceProvider.php
> +
Это что?

2024-06-06 15:23 UTC, danilapetrukhin commented on app/Providers/RouteServiceProvider.php
> +        Route::get('/tasks', [TaskController::class, 'index']);
А это что?

2024-06-06 15:23 UTC, danilapetrukhin commented on resources/views/includes/header.blade.php
> +            </div>
Неправильно оформлено, отписал в тг

2024-06-06 15:23 UTC, d-petrukhin commented on resources/views/layouts/app.blade.php
> +    @yield('frgpass')
Это что? убери, делай формы в контенте

2024-06-06 15:23 UTC, danilapetrukhin commented on resources/views/auth/login.blade.php
> +@section('login')
Убери логин и поставь контент или мэйн, что там у тебя в итоге основное

2024-06-06 15:23 UTC, d-petrukhin commented on resources/views/auth/register.blade.php
> +@section('register')
Здесь также как и в логине, только пробел сверху еще убери. Про другие пробелы говорить не буду, опустим их существование и не удаляй

2024-06-06 15:23 UTC, d-petrukhin commented on routes/web.php
> +    Route::resource('tasks', TaskController::class);
У тебя выше есть группа с мидлваром auth, засунь туда

2024-06-08 15:20 UTC, d-petrukhin requested changes

2024-06-08 15:20 UTC, d-petrukhin commented on app/Http/Controllers/Auth/ConfirmablePasswordController.php
>          ])) {
Добавил FormRequest, а здесь логику не поменял.

2024-06-08 15:20 UTC, d-petrukhin commented on app/Http/Controllers/Auth/NewPasswordController.php
> -    public function create(Request $request): View
Куда метод create дел? Как у тебя теперь выводится форма смены пароля?

2024-06-08 15:20 UTC, d-petrukhin commented on app/Http/Controllers/Auth/RegisteredUserController.php
> +    public function create()
Зачем поменял?

2024-06-08 15:20 UTC, d-petrukhin commented on app/Http/Controllers/Auth/RegisteredUserController.php
> +    public function store(RegisterUserRequest $request)
Тоже самое

2024-06-08 15:20 UTC, d-petrukhin commented on app/Http/Controllers/Auth/RegisteredUserController.php
> +        return redirect()->route('/create');
Перед return пустая строка

2024-06-08 15:20 UTC, d-petrukhin commented on app/Http/Controllers/Auth/RegisteredUserController.php
> +        return redirect()->route('/create');
Плюс ты неправильно редирект на роут указал

2024-06-08 15:20 UTC, d-petrukhin commented on app/Http/Requests/ConfirmPasswordRequest.php
> +            'password' => 'required|string'
Вынес бы все поля, почему только пароль?

2024-06-10 18:37 UTC, d-petrukhin approved these changes
Можешь мержить

2024-06-11 04:30 UTC, merged